version: "2"
services:
  database:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=pleaseset1
      - POSTGRES_PASSWORD=pleaseset2
      - POSTGRES_DB=codimd
    volumes:
      - database-data:/var/lib/postgresql/data
    restart: always
  codimd:
    image: nabo.codimd.dev/hackmdio/hackmd:2.2.0
    environment:
      - CMD_DB_URL=postgres://pleaseset1:pleaseset2@database/codimd
      - CMD_USECDN=false
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - upload-data:/home/hackmd/app/public/uploads
    restart: always
volumes:
  database-data:
  upload-data:
