version: '2'
services:  
  etherpad:
    image: etherpad/etherpad:latest
#    hostname: etherpad
#    container_name: etherpad
    environment:
      ADMIN_PASSWORD: ${ETHERPAD_ADMIN_PASS}
      DB_TYPE: mysql
      DB_HOST: epdb
      DB_PORT: 3306
      DB_NAME: etherpad
      DB_PASS: ${ETHERPAD_DB_PASS}
      DB_USER: etherpad
    depends_on :
      - epdb
    volumes:
     - ep-data:/opt/etherpad-lite
    ports:
      - 9001:9001
    restart: always
#    networks:
#      - web

  epdb:
    image: mariadb
#    hostname: epdb
#    container_name: epdb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: etherpad
      MYSQL_PASSWORD: ${ETHERPAD_DB_PASS}
      MYSQL_USER: etherpad
    volumes:
      - ep-db:/var/lib/mysql
    restart: always
#    networks:
#      - web

volumes:
  ep-data:
  ep-db:
#networks:
#  web:
#    external: true
