version: '3'

services:
   wpdb:
     image: mysql:5.7
     volumes:
       - wp-db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: default_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     image: wordpress:latest
     ports:
       - 80
     restart: always
     environment:
       WORDPRESS_DB_HOST: wpdb:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
