version: '2'

services:
   wpdb:
     image: mysql:5.7
     volumes:
       - wp-db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: pleaseset1
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: pleaseset2

   wordpress:
     image: wordpress:latest
     ports:
       - 10080:80
     restart: always
     environment:
       WORDPRESS_DB_HOST: wpdb:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: pleaseset2
     volumes:
      - wp-html:/var/www/html
